packages:
  - "apps/*"
  - "packages/*"

catalog:
  turbo: "2.8.10"
  "@turbo/gen": "2.8.10"
  eslint: "9.39.2"
  "@eslint/js": "9.39.2"
  eslint-plugin-turbo: "2.8.10"
  prettier: "3.8.1"
  typescript: "5.9.3"
  react: "19.2.4"
  react-dom: "19.2.4"
  "@types/react": "19.2.10"
  "@types/react-dom": "19.2.3"
  next-themes: "0.4.6"
  lucide-react: "0.574.0"
  zod: "4.3.6"
