import type { z } from "zod";

import type { envSchema } from "./env.schema.js";

export type AppEnv = z.infer<typeof envSchema>;

export const ENV_KEYS = {
  NODE_ENV: "NODE_ENV",
  PORT: "PORT",
  WEB_ORIGIN: "WEB_ORIGIN",
  SERVER_PUBLIC_ORIGIN: "SERVER_PUBLIC_ORIGIN",
  S3_ENDPOINT_URL: "S3_ENDPOINT_URL",
  S3_REGION: "S3_REGION",
  S3_ACCESS_KEY_ID: "S3_ACCESS_KEY_ID",
  S3_SECRET_ACCESS_KEY: "S3_SECRET_ACCESS_KEY",
  S3_BUCKET: "S3_BUCKET",
  S3_FORCE_PATH_STYLE: "S3_FORCE_PATH_STYLE",
  S3_PUBLIC_BASE_URL: "S3_PUBLIC_BASE_URL",
  DB_HOST: "DB_HOST",
  DB_PORT: "DB_PORT",
  DB_USER: "DB_USER",
  DB_PASSWORD: "DB_PASSWORD",
  DB_NAME: "DB_NAME",
  JWT_SECRET: "JWT_SECRET",
  AUTH_ADMIN_LOGIN_ID: "AUTH_ADMIN_LOGIN_ID",
  AUTH_ADMIN_PASSWORD: "AUTH_ADMIN_PASSWORD",
} as const;
